# Generated by Django 3.0.5 on 2020-05-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices_Payemnts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('outstanding', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medical_History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True)),
                ('phone', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.CharField(blank=True, max_length=16, null=True)),
                ('gender', models.CharField(max_length=6)),
                ('age', models.IntegerField(max_length=2)),
                ('address', models.CharField(blank=True, max_length=20, null=True)),
                ('bloodgroup', models.CharField(blank=True, max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Your_Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('consulting_doc', models.CharField(choices=[('Doc1', 'Doc1'), ('Doc2', 'Doc2'), ('Doc3', 'Doc3')], default='Doc1', max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Active', max_length=10)),
            ],
        ),
    ]
