# Generated by Django 3.0.5 on 2020-05-28 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_auto_20200528_0803'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical_history',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='age',
            field=models.IntegerField(max_length=2),
        ),
    ]
