# Generated by Django 3.0.5 on 2020-05-29 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0004_auto_20200528_1325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoices_payemnts',
            old_name='date',
            new_name='date1',
        ),
        migrations.RenameField(
            model_name='medical_history',
            old_name='date',
            new_name='date2',
        ),
        migrations.RemoveField(
            model_name='your_appointments',
            name='date_time',
        ),
        migrations.AddField(
            model_name='your_appointments',
            name='date1',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='your_appointments',
            name='time1',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
