# Generated by Django 3.0.5 on 2020-05-28 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('consulting_doc', models.CharField(choices=[('Doc1', 'Doc1'), ('Doc2', 'Doc2'), ('Doc3', 'Doc3')], default='Doc1', max_length=15)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Active', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('symptoms', models.CharField(blank=True, max_length=20, null=True)),
                ('prescription', models.CharField(blank=True, max_length=30, null=True)),
                ('patient_name', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
